import { Vehicle, Career, Partner } from './types';

export const SEED_VEHICLES: Vehicle[] = [
  {
    id: 'v1',
    brand: 'Pegassi',
    model: 'Zentorno',
    class: 'Super',
    price: 725000,
    plate: 'ZEN-001',
    mileage: 1200,
    fuelType: 'Petrol',
    drivetrain: 'AWD',
    performanceMods: 'Complete',
    securityMods: 'Complete',
    handlingMods: 'Partial',
    condition: 'Excellent',
    subwoofer: true,
    cargoSpace: 0,
    insurancePerDay: 1200,
    status: 'available',
    featured: true,
    imageUrl: 'https://placehold.co/800x450/1a1a1a/c0392b?text=Pegassi+Zentorno',
    soldCount: 4,
    createdAt: '2025-01-10T10:00:00Z',
  },
  {
    id: 'v2',
    brand: 'Dewbauchee',
    model: 'Vagner',
    class: 'Super',
    price: 1535000,
    plate: 'VAG-002',
    mileage: 800,
    fuelType: 'Petrol',
    drivetrain: 'AWD',
    performanceMods: 'Complete',
    securityMods: 'Partial',
    handlingMods: 'Complete',
    condition: 'Excellent',
    subwoofer: false,
    cargoSpace: 0,
    insurancePerDay: 1800,
    status: 'available',
    featured: true,
    imageUrl: 'https://placehold.co/800x450/1a1a1a/c0392b?text=Dewbauchee+Vagner',
    soldCount: 2,
    createdAt: '2025-01-12T10:00:00Z',
  },
  {
    id: 'v3',
    brand: 'Ocelot',
    model: 'Pariah',
    class: 'Sports',
    price: 1420000,
    plate: 'PAR-003',
    mileage: 3400,
    fuelType: 'Petrol',
    drivetrain: 'RWD',
    performanceMods: 'Partial',
    securityMods: 'None',
    handlingMods: 'Partial',
    condition: 'Good',
    subwoofer: true,
    cargoSpace: 1,
    insurancePerDay: 1500,
    status: 'available',
    featured: true,
    imageUrl: 'https://placehold.co/800x450/1a1a1a/c0392b?text=Ocelot+Pariah',
    soldCount: 6,
    createdAt: '2025-01-15T10:00:00Z',
  },
  {
    id: 'v4',
    brand: 'Grotti',
    model: 'Itali RSX',
    class: 'Super',
    price: 3465000,
    plate: 'RSX-004',
    mileage: 500,
    fuelType: 'Electric',
    drivetrain: 'AWD',
    performanceMods: 'Complete',
    securityMods: 'Complete',
    handlingMods: 'Complete',
    condition: 'Excellent',
    subwoofer: true,
    cargoSpace: 0,
    insurancePerDay: 2500,
    status: 'reserved',
    featured: false,
    imageUrl: 'https://placehold.co/800x450/1a1a1a/c0392b?text=Grotti+Itali+RSX',
    soldCount: 1,
    createdAt: '2025-01-18T10:00:00Z',
  },
  {
    id: 'v5',
    brand: 'Benefactor',
    model: 'Schlagen GT',
    class: 'Sports',
    price: 1295000,
    plate: 'SCH-005',
    mileage: 5200,
    fuelType: 'Petrol',
    drivetrain: 'RWD',
    performanceMods: 'None',
    securityMods: 'Partial',
    handlingMods: 'None',
    condition: 'Good',
    subwoofer: false,
    cargoSpace: 2,
    insurancePerDay: 1100,
    status: 'available',
    featured: false,
    imageUrl: 'https://placehold.co/800x450/1a1a1a/c0392b?text=Benefactor+Schlagen+GT',
    soldCount: 3,
    createdAt: '2025-01-20T10:00:00Z',
  },
  {
    id: 'v6',
    brand: 'Vapid',
    model: 'Dominator GTX',
    class: 'Muscle',
    price: 695000,
    plate: 'DOM-006',
    mileage: 9800,
    fuelType: 'Petrol',
    drivetrain: 'RWD',
    performanceMods: 'Partial',
    securityMods: 'None',
    handlingMods: 'None',
    condition: 'Fair',
    subwoofer: true,
    cargoSpace: 1,
    insurancePerDay: 700,
    status: 'available',
    featured: false,
    imageUrl: 'https://placehold.co/800x450/1a1a1a/c0392b?text=Vapid+Dominator+GTX',
    soldCount: 5,
    createdAt: '2025-01-22T10:00:00Z',
  },
  {
    id: 'v7',
    brand: 'Bravado',
    model: 'Gauntlet Hellfire',
    class: 'Muscle',
    price: 745000,
    plate: 'GHF-007',
    mileage: 7300,
    fuelType: 'Petrol',
    drivetrain: 'RWD',
    performanceMods: 'Complete',
    securityMods: 'Partial',
    handlingMods: 'Partial',
    condition: 'Good',
    subwoofer: false,
    cargoSpace: 1,
    insurancePerDay: 750,
    status: 'available',
    featured: false,
    imageUrl: 'https://placehold.co/800x450/1a1a1a/c0392b?text=Bravado+Gauntlet+Hellfire',
    soldCount: 7,
    createdAt: '2025-01-25T10:00:00Z',
  },
  {
    id: 'v8',
    brand: 'Canis',
    model: 'Kamacho',
    class: 'SUV',
    price: 450000,
    plate: 'KAM-008',
    mileage: 15000,
    fuelType: 'Diesel',
    drivetrain: '4WD',
    performanceMods: 'None',
    securityMods: 'Complete',
    handlingMods: 'None',
    condition: 'Fair',
    subwoofer: true,
    cargoSpace: 4,
    insurancePerDay: 500,
    status: 'available',
    featured: false,
    imageUrl: 'https://placehold.co/800x450/1a1a1a/c0392b?text=Canis+Kamacho',
    soldCount: 2,
    createdAt: '2025-01-28T10:00:00Z',
  },
  {
    id: 'v9',
    brand: 'Declasse',
    model: 'Granger 3600LX',
    class: 'SUV',
    price: 1605000,
    plate: 'GRN-009',
    mileage: 2100,
    fuelType: 'Petrol',
    drivetrain: 'AWD',
    performanceMods: 'Partial',
    securityMods: 'Complete',
    handlingMods: 'Partial',
    condition: 'Excellent',
    subwoofer: true,
    cargoSpace: 5,
    insurancePerDay: 1600,
    status: 'sold',
    featured: false,
    imageUrl: 'https://placehold.co/800x450/1a1a1a/c0392b?text=Declasse+Granger+3600LX',
    soldCount: 3,
    createdAt: '2025-02-01T10:00:00Z',
  },
  {
    id: 'v10',
    brand: 'Western',
    model: 'Nightblade',
    class: 'Motorcycle',
    price: 280000,
    plate: 'NB-0010',
    mileage: 4500,
    fuelType: 'Petrol',
    drivetrain: 'RWD',
    performanceMods: 'Partial',
    securityMods: 'None',
    handlingMods: 'Partial',
    condition: 'Good',
    subwoofer: false,
    cargoSpace: 0,
    insurancePerDay: 300,
    status: 'available',
    featured: true,
    imageUrl: 'https://placehold.co/800x450/1a1a1a/c0392b?text=Western+Nightblade',
    soldCount: 9,
    createdAt: '2025-02-05T10:00:00Z',
  },
];

export const SEED_CAREERS: Career[] = [
  {
    id: 'c1',
    title: 'Salesperson',
    department: 'Sales',
    description: 'Represent Lux Automotive on the showroom floor. Guide clients through our premium inventory and close high-value deals with professionalism and style.',
    requirements: 'Minimum 6 months RP sales experience. Professional IC conduct at all times. Available during peak server hours.',
    active: true,
    createdAt: '2025-02-01T10:00:00Z',
  },
  {
    id: 'c2',
    title: 'Human Resources',
    department: 'Human Resources',
    description: 'Be the backbone of our team. As part of the HR department at Lux Automotive, you will oversee recruitment, onboarding, and staff management. You\'ll ensure our team maintains the high standards Lux Automotive is known for, handle internal disputes, and support our people in performing at their best.',
    requirements: 'Strong interpersonal and communication skills. Experience with IC staff management or organisational RP. Ability to handle sensitive matters with discretion and professionalism.',
    active: true,
    createdAt: '2025-02-01T10:00:00Z',
  },
  {
    id: 'c3',
    title: 'Vehicle Supplier',
    department: 'Acquisitions',
    description: 'Source and evaluate incoming trade-ins and private seller vehicles. Conduct condition assessments and negotiate acquisition prices for the dealership.',
    requirements: 'Knowledge of GTA vehicle classes and market pricing. Strong negotiation RP skills.',
    active: true,
    createdAt: '2025-02-01T10:00:00Z',
  },
];

export const SEED_PARTNERS: Partner[] = [
  {
    id: 'p1',
    name: 'LS Customs',
    logoUrl: 'https://placehold.co/120x60/1a1a1a/c0392b?text=LS+Customs',
    description: 'Official modification partner. LS Customs provides exclusive discounts on upgrades for all Lux Automotive buyers.',
    website: '#',
    active: true,
  },
  {
    id: 'p2',
    name: 'Maze Bank',
    logoUrl: 'https://placehold.co/120x60/1a1a1a/c0392b?text=Maze+Bank',
    description: 'Preferred financing partner. Maze Bank offers competitive auto loan rates exclusively for our clientele.',
    website: '#',
    active: true,
  },
];
